// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

// Configuration that works with rustc < 1.71.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    erc1155
    (
        init => init
        issueFungibleToken => issue_fungible_token
        setLocalRoles => set_local_roles
        getBalances => balances
        getBalanceById => get_balance_by_id
        tokenCount => token_count
    )
}

multiversx_sc_wasm_adapter::async_callback! { erc1155 }
